site_name: Template geOrchestra

repo_url: https://github.com/georchestra/georchestra_documentation
repo_name: GitHub

docs_dir: docs
edit_uri: edit/main/docs/

theme:
  #name: 'mkdocs'
  name: 'readthedocs'

extra_css:
    - css/extra.css

# arborescence de premier niveau à gérer ici
nav:
    - Accueil: index.md 
    - Guide utilisateur: 
      - Prendre en main: prise_en_main.md
      - Utiliser: utiliser.md
    - Guides techniques:
      - Administrer: administrer.md
      - Installer: installer.md
      - Développer: developper.md