site_name: Template geOrchestra

repo_url: https://github.com/georchestra/georchestra_documentation
repo_name: GitHub

docs_dir: docs
edit_uri: edit/main/docs/

theme:
  # name: 'mkdocs'
  name: 'readthedocs'
  # name: material

extra_css:
    - css/extra.css

# arborescence de 1er et 2e niveau à gérer ici
# Ces entrées correspondent au modèle de documentation

nav:
    - Accueil: index.md 
    - Guide utilisateur:
        - Sommaire: guide_utilisateur/index.md
        - Prendre en main: guide_utilisateur/prise_en_main.md
        - Utiliser: guide_utilisateur/utiliser.md
    - Guides techniques:
        - Sommaire: guides_techniques/index.md
        - Administrer: guides_techniques/administrer.md
        - Installer: guides_techniques/installer.md
        - Développer: guides_techniques/developper.md

