site_name: My Docs

repo_url: https://github.com/MaelREBOUX/test-geor-doc
repo_name: GitHub

docs_dir: docs
edit_uri: edit/main/docs/

theme:
  #name: 'mkdocs'
  name: 'readthedocs'

extra_css:
    - css/extra.css
